 // Mock game data with real assets where available
const GAMES = [
  {
    id: 1,
    title: "Diablo IV",
    publisher: "Blizzard Entertainment",
    originalPrice: 69.99,
    salePrice: 34.99,
    salePercent: 50,
    genomeTags: ["Action RPG", "Dark Fantasy", "Multiplayer", "Open World", "Loot"],
    recommendation: "Fans of Path of Exile like",
    boxArt: "assets/diablo4-box.jpg",
    heroArt: "assets/diablo4-hero.jpg",
    heroTitledArt: "assets/diablo4-hero.jpg",
    screenshots: ["assets/diablo4-ss1.jpg", "assets/diablo4-ss2.jpg", "assets/diablo4-ss3.jpg", "assets/diablo4-ss4.jpg"],
    color: "#8b0000",
    gamePassTier: null,
    esrb: "M"
  },
  {
    id: 2,
    title: "Fallout 76",
    publisher: "Bethesda Game Studios",
    originalPrice: 39.99,
    salePrice: 9.99,
    salePercent: 75,
    genomeTags: ["RPG", "Open World", "Multiplayer", "Post-Apocalyptic", "Survival"],
    recommendation: "Because you played Fallout 4",
    boxArt: "assets/fallout76-box.jpg",
    heroArt: "assets/fallout76-hero.jpg",
    heroTitledArt: "assets/fallout76-hero.jpg",
    screenshots: ["assets/fallout76-ss1.jpg", "assets/fallout76-ss2.jpg", "assets/fallout76-ss3.jpg", "assets/fallout76-ss4.jpg"],
    color: "#2d5a1e",
    gamePassTier: "Game Pass Ultimate",
    esrb: "M"
  },
  {
    id: 3,
    title: "Halo Infinite",
    publisher: "343 Industries",
    originalPrice: 59.99,
    salePrice: 23.99,
    salePercent: 60,
    genomeTags: ["FPS", "Sci-Fi", "Multiplayer", "Campaign", "Arena"],
    recommendation: "Fans of Halo like",
    boxArt: "assets/halo-box.jpg",
    heroArt: "assets/halo-hero.jpg",
    heroTitledArt: "assets/halo-hero.jpg",
    screenshots: ["assets/halo-ss1.jpg", "assets/halo-ss2.jpg", "assets/halo-ss3.jpg", "assets/halo-ss4.jpg"],
    color: "#2d5a3d",
    gamePassTier: "Game Pass Ultimate",
    esrb: "T"
  },
  {
    id: 4,
    title: "Sea of Thieves",
    publisher: "Rare",
    originalPrice: 39.99,
    salePrice: 19.99,
    salePercent: 50,
    genomeTags: ["Adventure", "Multiplayer", "Pirates", "Open World"],
    recommendation: "Trending in your region",
    boxArt: "assets/seaofthieves-box.jpg",
    heroArt: "assets/seaofthieves-hero.jpg",
    heroTitledArt: "assets/seaofthieves-hero.jpg",
    screenshots: ["assets/seaofthieves-ss1.jpg", "assets/seaofthieves-ss2.jpg", "assets/seaofthieves-ss3.jpg", "assets/seaofthieves-ss4.jpg"],
    color: "#1a4a6a",
    gamePassTier: "Game Pass Ultimate",
    esrb: "T"
  },
  {
    id: 5,
    title: "Hi-Fi Rush",
    publisher: "Tango Gameworks",
    originalPrice: 29.99,
    salePrice: 14.99,
    salePercent: 50,
    genomeTags: ["Action", "Rhythm", "Colorful", "Hack and Slash"],
    recommendation: "Highly rated by players",
    boxArt: "assets/hifirush-box.jpg",
    heroArt: "assets/hifirush-hero.jpg",
    heroTitledArt: "assets/hifirush-hero.jpg",
    screenshots: ["assets/hifirush-ss1.jpg", "assets/hifirush-ss2.jpg", "assets/hifirush-ss3.jpg", "assets/hifirush-ss4.jpg"],
    color: "#8a1a3a",
    gamePassTier: "PC Game Pass",
    esrb: "T"
  },
  {
    id: 6,
    title: "Starfield",
    publisher: "Bethesda Game Studios",
    originalPrice: 69.99,
    salePrice: 41.99,
    salePercent: 40,
    genomeTags: ["Open World", "RPG", "Sci-Fi", "Exploration", "Action"],
    recommendation: "Fans of Skyrim like",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#1a3a5c",
    gamePassTier: "Game Pass Ultimate",
    esrb: "M"
  },
  {
    id: 7,
    title: "Forza Horizon 5",
    publisher: "Playground Games",
    originalPrice: 59.99,
    salePrice: 29.99,
    salePercent: 50,
    genomeTags: ["Racing", "Open World", "Multiplayer", "Arcade"],
    recommendation: "Because you played Forza Horizon 4",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#c45e1a",
    gamePassTier: "Game Pass Ultimate",
    esrb: "E"
  },
  {
    id: 8,
    title: "Fable",
    publisher: "Playground Games",
    originalPrice: 69.99,
    salePrice: 55.99,
    salePercent: 20,
    genomeTags: ["RPG", "Fantasy", "Action", "Story Rich"],
    recommendation: "Based on your wishlist",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#5a3a1a",
    gamePassTier: "Game Pass Essentials",
    esrb: "M"
  },
  {
    id: 9,
    title: "Avowed",
    publisher: "Obsidian Entertainment",
    originalPrice: 69.99,
    salePrice: 48.99,
    salePercent: 30,
    genomeTags: ["RPG", "Fantasy", "First Person", "Action"],
    recommendation: "Similar to games you own",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#3a1a5a",
    gamePassTier: "Game Pass Ultimate",
    esrb: "M"
  },
  {
    id: 10,
    title: "Flight Simulator",
    publisher: "Asobo Studio",
    originalPrice: 59.99,
    salePrice: 35.99,
    salePercent: 40,
    genomeTags: ["Simulation", "Flying", "Realistic", "Open World"],
    recommendation: "Popular with Game Pass members",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#1a3a7a",
    gamePassTier: "PC Game Pass",
    esrb: "E"
  },
  {
    id: 11,
    title: "Grounded",
    publisher: "Obsidian Entertainment",
    originalPrice: 39.99,
    salePrice: 15.99,
    salePercent: 60,
    genomeTags: ["Survival", "Co-op", "Crafting", "Adventure"],
    recommendation: "Friends are playing",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#4a6a1a",
    gamePassTier: "Game Pass Ultimate",
    esrb: "T"
  },
  {
    id: 12,
    title: "Hellblade II",
    publisher: "Ninja Theory",
    originalPrice: 49.99,
    salePrice: 34.99,
    salePercent: 30,
    genomeTags: ["Action", "Story Rich", "Dark Fantasy", "Psychological"],
    recommendation: "Because you played Hellblade",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#2a1a1a",
    gamePassTier: "Game Pass Ultimate",
    esrb: "M"
  },
  {
    id: 13,
    title: "Age of Empires IV",
    publisher: "Relic Entertainment",
    originalPrice: 59.99,
    salePrice: 23.99,
    salePercent: 60,
    genomeTags: ["Strategy", "RTS", "Historical", "Multiplayer"],
    recommendation: "Top rated in Strategy",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#6a5a1a",
    gamePassTier: "PC Game Pass",
    esrb: "T"
  },
  {
    id: 14,
    title: "Psychonauts 2",
    publisher: "Double Fine",
    originalPrice: 59.99,
    salePrice: 23.99,
    salePercent: 60,
    genomeTags: ["Platformer", "Adventure", "Comedy", "Colorful"],
    recommendation: "Because you liked Ori",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#4a1a6a",
    gamePassTier: "Game Pass Ultimate",
    esrb: "T"
  },
  {
    id: 15,
    title: "Deathloop",
    publisher: "Arkane Studios",
    originalPrice: 59.99,
    salePrice: 17.99,
    salePercent: 70,
    genomeTags: ["FPS", "Roguelike", "Immersive Sim", "Stealth"],
    recommendation: "Similar to Dishonored",
    boxArt: null,
    heroArt: null,
    screenshots: [],
    color: "#1a1a4a",
    gamePassTier: null,
    esrb: "M"
  }
];

// Bundle definitions
const BUNDLES = [
  {
    id: "b1",
    title: "Diablo IV — Complete Edition",
    publisher: "Blizzard Entertainment",
    bundleType: "stacked",
    bundleLabel: "Game + 4 DLCs",
    originalPrice: 89.99,
    salePrice: 44.99,
    salePercent: 50,
    mainGame: 1,
    includedIds: [1],
    dlcNames: ["Vessel of Hatred", "Season of Blood", "Abattoir of Zir", "Season of the Construct"],
    itemCount: 5,
    color: "#8b0000",
    genomeTags: ["Action RPG", "Dark Fantasy", "Open World"],
    recommendation: "The complete Diablo experience"
  },
  {
    id: "b2",
    title: "Xbox Essentials Bundle",
    publisher: "Xbox Game Studios",
    bundleType: "mosaic",
    bundleLabel: "5 Games",
    originalPrice: 249.99,
    salePrice: 79.99,
    salePercent: 68,
    mainGame: 3,
    includedIds: [3, 4, 5, 7, 11],
    dlcNames: [],
    itemCount: 5,
    color: "#107c10",
    genomeTags: ["Action", "Adventure", "Racing"],
    recommendation: "Best value bundle"
  },
  {
    id: "b3",
    title: "Starfield Premium Bundle",
    publisher: "Bethesda Game Studios",
    bundleType: "badge",
    bundleLabel: "Game + Season Pass",
    originalPrice: 99.99,
    salePrice: 64.99,
    salePercent: 35,
    mainGame: 6,
    includedIds: [6],
    dlcNames: ["Shattered Space", "Season Pass"],
    itemCount: 3,
    color: "#1a3a5c",
    genomeTags: ["Open World", "RPG", "Sci-Fi"],
    recommendation: "Includes all DLC"
  },
  {
    id: "b4",
    title: "Bethesda RPG Collection",
    publisher: "Bethesda Game Studios",
    bundleType: "split",
    bundleLabel: "3 Games",
    originalPrice: 179.99,
    salePrice: 59.99,
    salePercent: 67,
    mainGame: 2,
    includedIds: [2, 6, 9],
    dlcNames: [],
    itemCount: 3,
    color: "#2d5a1e",
    genomeTags: ["RPG", "Open World", "Story Rich"],
    recommendation: "Explore vast worlds"
  },
  {
    id: "b5",
    title: "Sea of Thieves — Deluxe Edition",
    publisher: "Rare",
    bundleType: "carousel",
    bundleLabel: "Game + 4 DLCs",
    originalPrice: 79.99,
    salePrice: 34.99,
    salePercent: 56,
    mainGame: 4,
    includedIds: [4],
    dlcNames: ["A Pirate's Life", "Season Pass", "Dark Relics", "Emporium Pack"],
    itemCount: 5,
    color: "#1a4a6a",
    genomeTags: ["Adventure", "Multiplayer", "Pirates"],
    recommendation: "The ultimate pirate experience"
  },
  {
    id: "b6",
    title: "Action Legends Pack",
    publisher: "Xbox Game Studios",
    bundleType: "count",
    bundleLabel: "4 Games",
    originalPrice: 199.99,
    salePrice: 69.99,
    salePercent: 65,
    mainGame: 5,
    includedIds: [5, 12, 14, 15],
    dlcNames: [],
    itemCount: 4,
    color: "#4a1a6a",
    genomeTags: ["Action", "Adventure", "Story Rich"],
    recommendation: "Hand-picked action hits"
  },
  {
    id: "b7",
    title: "Halo Infinite — Ultimate Edition",
    publisher: "343 Industries",
    bundleType: "stacked",
    bundleLabel: "Game + 3 DLCs",
    originalPrice: 89.99,
    salePrice: 39.99,
    salePercent: 56,
    mainGame: 3,
    includedIds: [3],
    dlcNames: ["Campaign Pass", "Multiplayer Premium", "Forge Expansion"],
    itemCount: 4,
    color: "#2d5a3d",
    genomeTags: ["FPS", "Sci-Fi", "Multiplayer"],
    recommendation: "The definitive Halo experience"
  },
  {
    id: "b8",
    title: "Open World Explorers",
    publisher: "Xbox Game Studios",
    bundleType: "mosaic",
    bundleLabel: "4 Games",
    originalPrice: 219.99,
    salePrice: 74.99,
    salePercent: 66,
    mainGame: 1,
    includedIds: [1, 2, 4, 10],
    dlcNames: [],
    itemCount: 4,
    color: "#1a5a3a",
    genomeTags: ["Open World", "Exploration", "Adventure"],
    recommendation: "Worlds without limits"
  },
  {
    id: "b9",
    title: "Fallout 76 — Platinum Edition",
    publisher: "Bethesda Game Studios",
    bundleType: "badge",
    bundleLabel: "Game + Season Pass",
    originalPrice: 79.99,
    salePrice: 24.99,
    salePercent: 69,
    mainGame: 2,
    includedIds: [2],
    dlcNames: ["Steel Dawn", "Expeditions", "Atlantic City"],
    itemCount: 4,
    color: "#2d5a1e",
    genomeTags: ["RPG", "Multiplayer", "Survival"],
    recommendation: "All expansions included"
  },
  {
    id: "b10",
    title: "Hi-Fi Rush + Friends",
    publisher: "Xbox Game Studios",
    bundleType: "split",
    bundleLabel: "3 Games",
    originalPrice: 119.99,
    salePrice: 44.99,
    salePercent: 63,
    mainGame: 5,
    includedIds: [5, 14, 11],
    dlcNames: [],
    itemCount: 3,
    color: "#8a1a3a",
    genomeTags: ["Action", "Platformer", "Co-op"],
    recommendation: "Colorful adventures await"
  },
  {
    id: "b11",
    title: "Sea of Thieves — Captain's Collection",
    publisher: "Rare",
    bundleType: "carousel",
    bundleLabel: "Game + 3 DLCs",
    originalPrice: 69.99,
    salePrice: 29.99,
    salePercent: 57,
    mainGame: 4,
    includedIds: [4],
    dlcNames: ["Captain's Voyage", "Skull Keep", "Legendary Shores"],
    itemCount: 4,
    color: "#1a4a6a",
    genomeTags: ["Adventure", "Pirates", "Multiplayer"],
    recommendation: "Set sail with everything"
  },
  {
    id: "b12",
    title: "Strategy Masters Bundle",
    publisher: "Xbox Game Studios",
    bundleType: "count",
    bundleLabel: "3 Games",
    originalPrice: 149.99,
    salePrice: 49.99,
    salePercent: 67,
    mainGame: 13,
    includedIds: [13, 10, 11],
    dlcNames: [],
    itemCount: 3,
    color: "#6a5a1a",
    genomeTags: ["Strategy", "Simulation", "RTS"],
    recommendation: "For the tactical mind"
  }
];

// Channel definitions with interaction types
const CHANNELS = [
  {
    id: 1,
    name: "Picked for you",
    subtitle: "Hover Scale — Item scales up to reveal screenshot slideshow on hover",
    interactionType: "hover-scale",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "recommendation" },
    gameIds: [1, 3, 5, 9, 12, 7]
  },
  {
    id: 2,
    name: "On Sale Now",
    subtitle: "Hover Slide-Up — Info panel slides up from bottom on hover",
    interactionType: "hover-slide-up",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "genome" },
    gameIds: [2, 4, 1, 13, 15, 5]
  },
  {
    id: 5,
    name: "Explore by Genre",
    subtitle: "Hover Flip — Card flips to reveal back side with screenshot/details",
    interactionType: "hover-flip",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "genome" },
    gameIds: [5, 14, 2, 4, 11, 8]
  },
  {
    id: 8,
    name: "Top Rated",
    subtitle: "Drawer Slide — Side drawer slides out with screenshot and details",
    interactionType: "drawer-slide",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "genome" },
    gameIds: [5, 3, 14, 2, 12, 7]
  },
  {
    id: 9,
    name: "Popular with Game Pass",
    subtitle: "Spotlight Focus — Focuses item by dimming siblings and scaling up",
    interactionType: "spotlight",
    formFactorOverride: null,
    contentConfig: { showPrice: false, secondaryInfo: "recommendation" },
    gameIds: [4, 11, 2, 13, 15, 10]
  },
  {
    id: 10,
    name: "Quick Resume",
    subtitle: "Bumper Snap — Use Tab/Shift+Tab to snap between items with scale animation",
    interactionType: "bumper-snap",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "genome" },
    gameIds: [4, 1, 8, 11, 3, 15]
  },
  {
    id: 12,
    name: "Friends are Playing",
    subtitle: "Trigger Zoom — Hold Space on focused item to zoom and preview",
    interactionType: "trigger-zoom",
    formFactorOverride: null,
    contentConfig: { showPrice: false, secondaryInfo: "recommendation" },
    gameIds: [2, 5, 10, 13, 14, 6]
  },
  {
    id: 13,
    name: "Leaving Game Pass Soon",
    subtitle: "Stick Focus — Hover or focus to scale up with slideshow overlay and info",
    interactionType: "stick-scroll",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "recommendation" },
    gameIds: [9, 12, 7, 15, 8, 6]
  },
  {
    id: 14,
    name: "Games You Might Like",
    subtitle: "Long Hover — Item expands after hovering for ~600ms to show slideshow and details",
    interactionType: "long-hover",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "recommendation" },
    gameIds: [1, 5, 3, 4, 2, 14, 7, 9]
  },
  {
    id: 15,
    name: "On Sale Now",
    subtitle: "Long Hover — Item expands after hovering for ~600ms to show slideshow and details",
    interactionType: "long-hover",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "recommendation" },
    gameIds: [2, 4, 13, 15, 7, 11, 3, 8]
  },
  {
    id: 16,
    name: "Popular with Game Pass",
    subtitle: "Long Hover — Item expands after hovering for ~600ms to show slideshow and details",
    interactionType: "long-hover",
    formFactorOverride: null,
    contentConfig: { showPrice: false, secondaryInfo: "recommendation" },
    gameIds: [6, 7, 8, 9, 10, 12, 1, 4]
  },
  {
    id: 17,
    name: "New & Trending",
    subtitle: "Long Hover — Item expands after hovering for ~600ms to show slideshow and details",
    interactionType: "long-hover",
    formFactorOverride: null,
    contentConfig: { showPrice: true, secondaryInfo: "genome" },
    gameIds: [3, 11, 14, 15, 13, 5, 2, 6]
  }
];
